### ISSUE TITLE
Problem with Varchar(max)

### ISSUE THREAD

**Issue by bms-dwh** [pacman82/arrow-odbc-py#11]
Got an error when trying to extract a table with varchar(max). However, the error message was not that clear:

arrow_odbc.error.Error: ODBC reported a display size of 0.

Assume it is related to this issue:
https://github.com/pacman82/odbc2parquet/issues/59

Could work around by converting it to varchar(8000).

OS: Ubuntu 20.04
Driver: ODBC Driver 17 for SQL Server
Source: MS SQL Server 2019
Python Version: 3.9

**Comment by pacman82** [comment]
Hi Dominik,

thanks for reporting this. You are right to assume that it has the same root cause than pacman82/odbc2parquet#59. Unbounded columns and bulk fetches are not necessarily a good combination. Eventually I will apply the same fix to all affected artifacts. Hopefully if it works, we can query the majority of the fields using a reasonably sized buffer. The elements who are larger than the element size of the buffer will be streamed however from the database, so that large values are not truncated. That solution however is a bit involved and requires some groundwork in the `odbc-api` (<https://github.com/pacman82/odbc-api>) crate. It is not my priority at the moment however, but I'll eventually get to it.

Meanwhile improving the error message is a good mitigation. Also the workaround of either casting in the query or manipulating the database schema is exactly the right thing to do. Chances are, if each value would REALLY be several GB large people wouldn't care about bulk fetching them.

Cheers, Markus

**Comment by bms-dwh** [comment]
Hi Markus
Previously, I was using the turbodbc package a lot. They "solved" the problem with a parameter to define the character limit:
https://turbodbc.readthedocs.io/en/latest/pages/advanced_usage.html?highlight=max#limit-varchar-results-to-max
Maybe that would be something to consider.

Thanks a lot for your work.

Best regards,
Dominik

**Comment by pacman82** [comment]
It's something to consider. The drawbacks are pretty obvious though.

* (Mostly) silent truncation of values
* One size fits all for all columns

Admittedly the proper way of doing it might take me longer, but the result will be way more satisfying. However if demand on the user side becomes louder, or someone does a reasonable PR, I am game for an intermediate solution, too. I remember applying the same hack to `odbcsv` for a user working with Snowflake DB. Until when I'll hope however that the casts hold the line.

**Comment by bms-dwh** [comment]
The table I had a problem with was varchar(max) but all the values were null -just poor design. However, I can already fix them on my side when creating the query. So no worries. 

The UTF-8 bug would be way more appreciated :-)

**Comment by pacman82** [comment]
The library now emmits a good error message. Changed the label from Bug to enhancment, because there might be a possibility to handle this gracefully in the future.

**Comment by pacman82** [comment]
Sorry for the late response, this issue is at least partially solved, since May 6th or release `1.20`. It introduced an optional parameter for specifying an upper bound. See: <https://github.com/pacman82/arrow-odbc-py/blob/f4842fee817ea38d87c0439638f2485d27abbb6f/python/arrow_odbc/reader.py#L95>

Don't know why I did not think about this issue 😅 

Cheers, Markus

Please reopen, if there should still be a need for another solution.
