### ISSUE TITLE
insert_into_table fails

### ISSUE THREAD

**Issue by aersam** [pacman82/arrow-odbc-py#36]
Hi Markus again ;)

I try to just read a parquet file and call insert_into_table with the most recent pyarrow version:
``` python
from pyarrow import Table
import pyarrow.parquet as pq
from arrow_odbc import insert_into_table


reader: Table = pq.read_table(tf)
insert_into_table(reader, chunk_size, table, connection_string)
```
I get this error:
`AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute '_export_to_c'`

**Comment by pacman82** [comment]
This is what I get for using private functions, I guess. Would need to look into it. As a workaround you could look into `odbc2parquet` which does have an `insert` option.

**Comment by pacman82** [comment]
Hello @aersam ,

this is more likely an UX issue than a Bug. Inserting from a parquet file working fine. Please note that the insert works on a RecordBatchReader, rather than a table.

See: <https://github.com/pacman82/arrow-odbc-py/blob/3945998e8b4cca5a190f744f6b1cdb1c11ca5403/tests/test_arrow_odbc.py#L473>

We could of course think about providing an insert function based on a table, or improve the interface otherwise, to avoid such confusion.

**Comment by aersam** [comment]
Ok, tried adjusting my code and it now fails silently - maybe a rust panic? How do I diagnose this?

**Comment by pacman82** [comment]
* Would you have a small parquet file you could check into a branch which could help me reproduce?
* What kind of database are you using?
* What operating system are you on?

**Comment by aersam** [comment]
It's confidential data but I can try to generate a "fake" one which causes the error.

Operating System: Windows 10 (production will be Azure Functions Linux, which is similar to Ubuntu I think)
Database: Azure SQL Database, probably close to SQL Server 2022. I'm using ODBC Driver 17 as v18 is not available in Azure Functions yet

**Comment by pacman82** [comment]
If you want you could also share your code

**Comment by aersam** [comment]
here's my target table: 

```sql

CREATE TABLE [lake_import].[customer_sales_group](
	[customer_id] [nvarchar](20) NULL,
	[sales_group_id] [nvarchar](4) NULL,
	[sales] [float] NULL,
	[margin] [float] NULL,
	[year] [int] NULL,
	[month] [int] NULL,
	[sales_lager] [float] NULL,
	[margin_lager] [float] NULL,
	[sales_transit] [float] NULL,
	[margin_transit] [float] NULL
)
```

no indexes, no primary key

**Comment by aersam** [comment]
> If you want you could also share your code

well, will try to create a minimal repo. the code relies on a rest service delivering the parquets...

**Comment by aersam** [comment]
Could it be that passing ##globaltemp table is the issue?

**Comment by aersam** [comment]
Ok, here we go. Python code:

```
import pyarrow.parquet as pq
from arrow_odbc import insert_into_table
from pyarrow import Table, RecordBatch, RecordBatchReader
import pyarrow as pa

tbl: Table = pq.read_table("repo.parquet")
print(tbl.to_string(preview_cols=tbl.num_columns))
connection_string = "Server=SERVER.database.windows.net;Database=DB;Authentication=ActiveDirectoryInteractive;Encrypt=yes;ConnectRetryCount=3;DRIVER=ODBC Driver 17 for SQL Server"
table = "lake_import.customer_sales_group"
chunk_size = 4000
schema = tbl.schema
batches = tbl.to_batches(chunk_size)
reader = RecordBatchReader.from_batches(schema, batches)
insert_into_table(reader, chunk_size, table, connection_string)
```
Output:
![image](https://user-images.githubusercontent.com/5270024/228216036-a705b185-c0af-4fdf-b056-779933996a2f.png)

Data is here:
[repo.zip](https://github.com/pacman82/arrow-odbc-py/files/11088533/repo.zip)

Is is a problem to insert large_string into nvarchar(4) ? I will execute this with a global temp table in the end, but it seems that's not the issue

**Comment by pacman82** [comment]
I could reproduce the issue here: <https://github.com/pacman82/arrow-odbc-py/tree/reproduce-bug>

Then I have time, I'll try to minimize the example further. Are all columns needed to reproduce. Must I start from a parquet file and so on. I think after that I'll have some idea how to reproduce it in pure Rust.

Currently I can not tell if the access violation is a consequence from panicing in Rust while running in the python interpreter or if there is no panic and the access violation is the cause of it stopping. I'll hope a minimal example will yield the answer.

Thanks for bringing the issue to my attention.

**Comment by pacman82** [comment]
Hello @aersam ,

got to play around a bit more with this, this evening, and I think I got a more minimal example reproducing it. Parquet is only indirectly involved. PyArrow translates your file into a table with a schema containing columns of type `large_string` it seems to be this column type which breaks `arrow-odbc-py`. I can reproduce the bug with essentially this piece of code:

```python
    schema = pa.schema([("a", pa.large_string())])

    def iter_record_batches():
        # The string value is not actually large, just the schema information allows it to be
        yield pa.RecordBatch.from_arrays([pa.array(["Hello"])], schema=schema)

    reader = pa.RecordBatchReader.from_batches(schema, iter_record_batches())

    # When
    insert_into_table(
        connection_string=MSSQL, chunk_size=20, table=table, reader=reader
    )
```

For fun and games I inserted your Parquet file using `odbc2parquet` (which went fine). I also queried the data then back into a parquet file (again using `odbc2parquet`). Which left me with a similar parquet file, mostly different that it was written in an older version of the parquet file specification. Using `pyarrow` it translated into an arrow table containing just plain `string`s (rather than `large_string`s) and inserted fine.

Next time I have some spare time on my hands, I want to see why it stops rather than forwarding an exception. After that eventually there can be support for `large_string`s.

Cheers, Markus

**Comment by aersam** [comment]
Ok, thanks! I think strings beyond 2GB are not a frequent use case, but it seems some popular libs generate large_string types regardless of the actual size. My col had a max size of 4 chars... I used polars and pyarrow, must be one of them

**Comment by pacman82** [comment]
> I think strings beyond 2GB are not a frequent use case, but it seems some popular libs generate large_string types regardless of the actual size.

Inserting `large_string` will now work starting with `arrow-odbc-py 0.3.14` which has been released.

For convinience a `from_table_to_db` function has also been added. Inserting from a `pyarrow` table rather than a `RecordBatchReader`.

Cheers, Markus
