### ISSUE TITLE
Cannot install `arrow-odbc` on Apple Silicon Macs

### ISSUE THREAD

**Issue by alexander-beedie** [pacman82/arrow-odbc-py#54]
Not sure how much effort would be required to build suitable wheels for distribution (I believe GitHub does offer the necessary runners these days?), but would be _great_ to be able to install on modern Macs without having to compile locally (which I tried, but temporarily gave up on as it was getting a little non-trivial).

`pip` will attempt to compile it on download, but fails to resolve the relevant paths for linking (assuming you have already downloaded the necessary libraries), etc...😅 

<img width="607" src="https://github.com/pacman82/arrow-odbc-py/assets/2613171/de2aa24f-a12d-4692-a409-e27980c73dd2" />

**Comment by pacman82** [comment]
Hello @alexander-beedie ,

thanks for reporting the issue. Yes, this would be straight forward if GitHub would offer ARM runners. Yet it doesn't. Not to look a gift horse in the mouth though. It is awesome that in this day and age I get this much infrastructure for free anyway.

Sadly I can not see the entire error based on the provided screenshot. The artefact should build nicely on ARM though. The workflow files in this repository should give some hints on what is required to build. On the top of my head:

You need to install `unixodbc`. You can use brew for this, but last time I had access to an ARM brew put the binaries in different directories on ARM systems, as opposed to other platforms. `cargo` would not be able to find and link them as a result. This might be outdated knowledge though. I would recommend installing `unixodbc` from source. See also the ARM section of the odbc-sys Readme: <https://github.com/pacman82/odbc-sys>. UnixODBC is both a bulid and a runtime dependency.

The second thing you need for the build to work is a rust toolchain, including its build and package manager `cargo`. Visit <https://rustup.rs> and follow the instruction. The latest stable toolchain with default options always works.

Feel free to come back here, if you get stuck.

Best, Markus

**Comment by alexander-beedie** [comment]
> thanks for reporting the issue. Yes, this would be straight forward if GitHub would offer ARM runners. Yet it doesn't. 

Ahh, I should have been much more specific that the official Apple Silicon runners have only been available (in public beta) for -literally- a few days (I could have sworn they cam out earlier, but apparently not) ;) 
* https://github.com/actions/runner-images/issues/8439

**Comment by pacman82** [comment]
Cool, the blog post mentions some cost for these runners though. I already give my spare time maintaining this. I do not feel inclined to pay on top of it.

**Comment by alexander-beedie** [comment]
> Cool, the blog post mentions some cost for these runners though. I already give my spare time maintaining this. I do not feel inclined to pay on top of it.

Ahh, didn't spot that, my bad - not to worry, entirely understandable!
Thanks  ;)

**Comment by pacman82** [comment]
All good. Improving documentation to build help build locally is an entirely different beast though. Also, recently there has been some effort into making `arrow-odbc` available via the `conda-forge` channel. ARM pipeline is currently broken, but it used to work, and is likely to do so again in the future. So if you have anaconda or a similar package manager installed you can use that to install `arrow-odbc` without building locally yourself.

Best, Markus

**Comment by pacman82** [comment]
Hello @alexander-beedie and @ldacey

reopened the issue, because I saw you both mentioning build errors on M1 machines. Sadly I do not have access to one to try myself, but it was one of my core goals to make building and updating `arrow-odbc` way easier compared to other libraries, by only relying on C-Interfaces to cross the language barrier and not be tied to any C++ ABI or system provided boost version.

With a little bit of help I could probably provide a good description on how to build on M1. If you have access to one of these machines and one of you would be up for a pair programming (well, building) session I would be game.

I am located in the Central European Time zone FYI.

Best, Markus

**Comment by alexander-beedie** [comment]
> With a little bit of help I could probably provide a good description on how to build on M1. If you have access to one of these machines and one of you would be up for a pair programming (well, building) session I would be game.

Sounds like a plan; would be happy to help  :)
As far as timezones go, I'm only 2 hours off CET, so shouldn't be too challenging to find a good time.

**Comment by pacman82** [comment]
@alexander-beedie I invited you to a repository with my contact data in order to connect.

**Comment by tomsej** [comment]
For anyone who is trying to install `arrow-odbc` on Apple Silicon. First you need to install `unixodbc` - `brew install unixodbc`.
Now if you try to install `arrow-odbc` you will get following error:
```
    = note: ld: warning: ignoring duplicate libraries: '-lc', '-lm'
            ld: warning: search path '/Users/radek.tomsej/lib' not found
            ld: library 'odbc' not found
            clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
All you need to do is create a simling to specified search path: `sudo ln -s /opt/homebrew/lib /Users/radek.tomsej/lib`. Then you are able to install it.

**Comment by pacman82** [comment]
Thanks again @tomsej ,

this worked again here: <https://github.com/pacman82/arrow-odbc/issues/75#issuecomment-1797394808>

**Comment by pacman82** [comment]
Thanks @ldacey for confirming it is working#

**Comment by radeva** [comment]
@pacman82 In case you need M1 runners in the future, you can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a **free tier for OSS projects** (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)

**Comment by pacman82** [comment]
Hello @radeva ,

I am short on time atm. , yet this is indeed interesting. Soon, as I find myself having some time to spare, I will give it a look.

Best, Markus

**Comment by pacman82** [comment]
Hello @radeva ,

thanks to FlyCI's free tier both `arrow-odbc` and `odbc2parquet` now enjoy a release for Mac ARM 64. Thank you!

Best, Markus
