### ISSUE TITLE
Length indicator must be non-negative.: TryFromIntError()

### ISSUE THREAD

**Issue by tomsej** [pacman82/arrow-odbc-py#68]
Hi, I am using `arrow-odbc-py` with `db2`. I have a table that has column `zip` that is `VARCHAR(16)`. I am using this code to run it:
```
    result = read_arrow_batches_from_odbc(
        query=sql,
        connection_string=conn,
        batch_size=batch_size,
        max_text_size=4000,
    )
```
And I am getting this error:
<img width="1458" alt="image" src="https://github.com/pacman82/arrow-odbc-py/assets/6624716/8fe79d67-cc30-43d0-b1b4-8bfcc5469834">

Seems the problem is when the column contains null values.

Any idea, how can I deal with it? Thanks a lot!

**Comment by pacman82** [comment]
@tomsej Thanks for reporting the issue.

**Comment by pacman82** [comment]
Note to self: <https://github.com/pacman82/odbc-api/blob/a45b2023d14d2cdcdc632c3a7e80207266bea659/odbc-api/src/buffers/indicator.rs#L15C1-L29C1>

**Comment by pacman82** [comment]
Link to issue about erroneous indicators reported by db2 driver: <https://github.com/pacman82/odbc-api/issues/398>

**Comment by pacman82** [comment]
Hi @tomsej , this is a symptom of a known (to me) bug of the db2 ODBC driver. This bug is really serious as reporting basically random memory garbage as string length indicators can have all kinds of side effects for data integrity and security. I tried to report that bug. Yet I am a maintainer of an Open Source artifact, not a paying customer of IBM. If there is a process for me to tell them about an error in their ODBC driver, I did not find it. I even created an IBM account, but in the end I always hit some kind of red tape. After spending almost an entire Saturday on this I gave up.

If you would be able to open a Bug report with them, I am willing to help and precisely what part of the ODBC spec they are violating.

In two sentences: They **must not** assume that an application relies on terminating zeroes to determine string lengths. If an indicator buffer is bound to a column, after a bulk fetch the values within it must be either `-1` to indicate a `NULL` or be the length of the string without the terminating zero.

> Seems the problem is when the column contains null values.

This is an interesting observation. I am curious. Does this error only occur if the Schema allows for NULL, or must there be actual NULL values in the fields. 

There would be ways to work around this problem which could do the right thing most of the time. However I suspect sometimes they would silently loose data. I maybe wrong about this, but at the moment I am afraid to publish a "fix" which might harm someones data integrity. A fix by IBM is IMHO by far the best solution.

Best, Markus

**Comment by pacman82** [comment]
Hello @tomsej ,

`arrow-odbc 2.0.3` is released. It contains a workaround for IBM DB2. I could not test it against this database, so please tell me if this works.

Best, Markus

**Comment by tomsej** [comment]
Thanks a 💯 @pacman82 for working during the weekend!!! Indeed, working with DB2 can be challenging :) (it sucks actually). Therefore, I don't anticipate any significant changes happening in the near future. Even if we would able to fill the bug report 😢 
The workaround you have deployed is way better than previous version, but there is an issue when you have a column that is mandatory (schema does not allow Nulls) and value is empty string. Than I get a error (column name is STRING): 

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-odbc-4.1.0/src/reader/to_record_batch.rs:103:85:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Column 'STRING' is declared as non-nullable but contains null values")
```

That is something I am able to live with, since I can write a condition like `case when string = '' then ' ' else string`.

Once again, I deeply appreciate your efforts. Thank you very much for what you are doing!

**Comment by pacman82** [comment]
Thank you @tomsej ! Weird as it may sound, I find contributing to Open Source is a relaxin spare time activity. At least ever since Conway's law forced me into management. It is extra rewarding if the work is appreciated, though.

To the issue at hand. The indicators (i.e. the thing which is garbage memory in the db2 driver) is not only responsible for reporting string lengths, but is supposed to be `-1` for NULL strings. Since they are garbage, I have to ignore them all, though. My not so well thought out workaround, had been to simply treat empty strings as NULL.

I never did test with a mandatory schema though. I wonder if a better workaround would be, to never return NULL but to just always return the string, which may be empty. Rational: Due to the invalid indicator buffer empty string and NULL are indistiguishable for the application. At least the empty string representation can be consistentently applied.

Of course depending on the situation you would need to map empty string to NULL in application code.

**Comment by keraion** [comment]
Hey @tomsej, I noticed something from your [prior issue](https://github.com/pacman82/arrow-odbc-py/issues/60#issue-1975846903) that you were using `libdb2.so` as your driver:

```ini
[DB2 Driver]
Description = DB2 Driver
Driver      = /var/lang/lib/python3.10/site-packages/clidriver/lib/libdb2.so
FileUsage   = 1
DontDLClose = 1
```

However, you may want to use `libdb2o.so` instead as noted by [this documentation](https://www.ibm.com/docs/en/db2/11.5?topic=manager-installing-unixodbc-driver). I've noticed issues before using the `libdb2.so` driver and [IBM's documentation](https://www.ibm.com/docs/en/db2/11.5?topic=environment-setting-up-odbc-linux-unix) states that it is used for the 32-bit ODBC Driver Manager as well as the 32-bit and 64-bit CLI application. The `libdb2o.so` library on the otherhand, is for the 64-bit ODBC Driver Manager.

The change to the `odbcinst.ini` file should be pretty straightforward, but unfortunately the `libdb2o.so` file is located behind one of IBM's login walls unlike the `libdb2.so` file.

**Comment by pacman82** [comment]
Also, arrow-odbc 2.0.4 has been released. It no longer maps empty strings to NULl

**Comment by rupurt** [comment]
@tomsej super interesting...

Where did you download the `libdb2o.so` driver? The packages provided [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/) only provide `libdb2.so`?

**Comment by rupurt** [comment]
@tomsej @keraion super interesting...

Where did you download the `libdb2o.so` driver? The packages provided [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/) only provide `libdb2.so`?

**Comment by keraion** [comment]
@rupurt they are behind a login on Fix Central, but [this](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%20Management&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.*&platform=All&function=all) should get you about 90% there. 

I'd suggest selecting the "odbc_cli" version (e.g. DSClients-linuxx64-odbc_cli-11.5.9.0-FP000) for your platform, version, and fix pack.

**Comment by rupurt** [comment]
Ugggg, I hate fix central. I'm from Australia and for some reason can't download anything from there because it says it's against US export restrictions.

**Comment by rupurt** [comment]
Managed to grab `libdb2o.so`.

I'm still running into the non-nullable column error on `arrow-odbc` `2.1.4` and the latest on `main` with both drivers.

```shell
evac odbc sql -c 'SELECT * FROM DB205DBA.TINCNTL'
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-odbc-6.1.0/src/reader/to_record_batch.rs:103:85:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Column 'INV_NM' is declared as non-nullable but contains null values")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by pacman82** [comment]
Hi, thanks for all the information. Minor nitpick, this is a not a segfault, nobody is accessing invalid memory. Instead the driver returned a value to unfit for a signed 64 Bit integer. Interestingly enough the value is supposed to be `-98` given your issue in `odbc-api` (<https://github.com/pacman82/odbc-api/issues/509>). My understanding is the driver update did fix this for you?

The error tomsej  reported has the same symptom, but the cause is a different one.

**Comment by pacman82** [comment]
@rupurt You might be able to mitigate the error about the non nullable columns by providing an arrow schema (using the `schema` parameter), with nullable columns. Other than that, this seems like a driver error (again). It just should not claim a column to be non-nullable, if it in actuality conatains nulls.

**Comment by rupurt** [comment]
@pacman82 thanks for the clarification. I've updated the title.

This is the verbose output I get for the nullability error.

```shell
> evac odbc sql -c 'SELECT NUM FROM MYSCHEMA.MYTABLE' -v
DEBUG - ODBC Environment created.
DEBUG - SQLAllocHandle allocated connection (Dbc) handle '0x21976e0'
DEBUG - Database managment system name as reported by ODBC: DB2
DEBUG - ODBC driver reported for column 0. Relational type: Varchar { length: Some(20) }; Nullability: NoNulls; Name: 'NUM';
DEBUG - SQLColAttribute called with attribute 'ConciseType' for column '1' reported 12.
DEBUG - SQLColAttribute called with attribute 'DisplaySize' for column '1' reported 20.
DEBUG - Relational type of column 0: Varchar { length: Some(20) }
INFO - Column 'INV_NM'
Bytes used per row: 89
INFO - Total memory usage per row for single transit buffer: 89
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-odbc-6.1.0/src/reader/to_record_batch.rs:103:85:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Column 'NUM' is declared as non-nullable but contains null values")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by pacman82** [comment]
> DEBUG - ODBC driver reported for column 0. Relational type: Varchar { length: Some(20) }; Nullability: NoNulls; Name: 'NUM';

Seems, `db2` driver got that wrong.

**Comment by pacman82** [comment]
@rupurt would you kindly copy the log and create a separate issue for this?

**Comment by pacman82** [comment]
I would like to link to a dedicated issue in the documentation

**Comment by rupurt** [comment]
@pacman82 done https://github.com/pacman82/arrow-odbc-py/issues/78

I've also added the column definition if it helps
