### ISSUE TITLE
Return pyarrow.RecordBatchReader from read_arrow_batches_from_odbc

### ISSUE THREAD

**Issue by rupurt** [pacman82/arrow-odbc-py#83]
This will allow `arrow-odbc` to be used with the [pyarrow dataset API](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html)

https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatchReader.html

**Comment by pacman82** [comment]
Nice idea, do you have a specific thing you want to do in mind? I wonder if, as a first step it would be sufficient to add a few methods and inherit, or if `arrow-odbc` would have to switch to the arrow stream interface altogether.

**Comment by pacman82** [comment]
Note to self: <https://arrow.apache.org/docs/format/CStreamInterface.html>

**Comment by rupurt** [comment]
I'm trying to plug it into the [duckdb arrow reader](https://duckdb.org/docs/guides/python/sql_on_arrow.html#apache-arrow-recordbatchreaders).

**Comment by pacman82** [comment]
How is `arrow-odbc` helpful at all if you already have a reader emitting batches?

**Comment by rupurt** [comment]
What I really want is the reader emitting the arrow batch interface so duckdb can integrate with it directly. There's also a bunch of other arrow API's that only work with known arrow types. I've currently wrapped them but ideally I wouldn't need to.

**Comment by pacman82** [comment]
The part that confuses me is that following the link to the duckdb arrow reader interface, it seems to me that this is an API that **emits** record batches, but what I read in your description is that you want to **consume** record batches emitted by `arrow-odbc`. I would like to understand into which API call you want to put the RecordBatchReader which would be emitted by `read_arrow_batches_from_odbc`.

**Comment by rupurt** [comment]
This is the [documentation](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatchReader.html) for Arrow batch reader. DuckDB can consume that natively.

**Comment by rupurt** [comment]
cpp docs

- https://arrow.apache.org/docs/cpp/api/dataset.html#classarrow_1_1dataset_1_1_scanner_1a4c39dc64f6939bc205ee9a7ca9fac8a7
- https://arrow.apache.org/docs/cpp/api/table.html#_CPPv4N5arrow17RecordBatchReaderE

**Comment by timrburnham** [comment]
I frequently use this pattern in my ETLs, using DuckDB for joining cross-database sources and transformation logic:

```python
query = arrow_odbc.read_arrow_batches_from_odbc(sql, connect_string)
reader = pyarrow.RecordBatchReader.from_batches(query.schema, query)

with duckdb.connect("temp_db.duckdb") as duck:
    duck.from_arrow(reader).create("my_table")
    duck.sql("select * from my_table").to_parquet("output.parquet")
```

(Example uses DuckDB's lazy Relational API). An arrow-odbc function which returns a RecordBatchReader directly would be nice to have, rather than converting the BatchReader iterator on line 2.

**Comment by rupurt** [comment]
Thanks @timrburnham thats essentially how I’m currently wrapping it. Not too much effort but would be nice to skip that step.

**Comment by pacman82** [comment]
Closing this issue. Some final notes on design here, so I remember myself.

Inheriting directly from PyArrows `RecordBatchReader` would imply using its C-Interface exclusively. It is basically a virtual function table + pointer to the object. This interface is not. So I can not come up with C-Function of my own which I want to support. This is fine to a degree, because I should not be able to extend the contract of a third party library. It is also hard to extend for my specialization of the contract.

Any of this would actually not be a problem, if `DuckDb` would stick to the generic roots of Python. Ironically DuckDBs python API does not use Duck typing. If so, it could all be solved by choosing the same method names for this library and PyArrow. Instead it seems to me DuckDB chooses to explicitly check for inheritance of that interface.

Here the two philosophies of inherting to be reused and inherting to reuse clash.

There may be a solution space in which I still extend the Arrow C-Interface, by directly accessing the handle pointer in their struct. Yet I would likely need to make assumptions of how the PyArrow interacts with its C-Interface. E.g. in cases there the schema whould change, because we go to the next result set.

For now I find it safer to have an ODBC specific interface and a PyArrow interface and an explicit conversion function between them.

Best, Markus
